AWSTemplateFormatVersion: '2010-09-09'
Description: Medicare Hub - Parent stack orchestrating nested phases via TemplateURLs

Parameters:
  Phase1TemplateUrl:
    Type: String

  Phase2TemplateUrl:
    Type: String

  Phase3TemplateUrl:
    Type: String

  Phase4TemplateUrl:
    Type: String

  Phase5TemplateUrl:
    Type: String

  KeyPairName:
    Type: String
    Default: ""

  DbUsername:
    Type: String
    Default: admin

  DbPasswordParameterName:
    Type: String
    Default: /medicarehub/db/master_password
    Description: Name of SSM SecureString parameter that stores the RDS master password

  WebsiteContentBucketName:
    Type: String

  DomainName:
    Type: String

Resources:
  # Phase 1 - Network (uses its own defaults; no params needed)
  Phase1Network:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref Phase1TemplateUrl

  # Phase 2 - EFS (needs VPC + private subnets + app SG from Phase 1)
  Phase2EFS:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref Phase2TemplateUrl
      Parameters:
        VpcId: !GetAtt Phase1Network.Outputs.VpcId
        PrivateSubnetAId: !GetAtt Phase1Network.Outputs.PrivateSubnetAId
        PrivateSubnetBId: !GetAtt Phase1Network.Outputs.PrivateSubnetBId
        AppSecurityGroupId: !GetAtt Phase1Network.Outputs.AppSecurityGroupId

  # Phase 3 - RDS (needs same VPC/subnets/SG; creds from parent)
  Phase3RDS:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref Phase3TemplateUrl
      Parameters:
        VpcId: !GetAtt Phase1Network.Outputs.VpcId
        PrivateSubnetAId: !GetAtt Phase1Network.Outputs.PrivateSubnetAId
        PrivateSubnetBId: !GetAtt Phase1Network.Outputs.PrivateSubnetBId
        AppSecurityGroupId: !GetAtt Phase1Network.Outputs.AppSecurityGroupId
        DbUsername: !Ref DbUsername
        DbPasswordParameterName: !Ref DbPasswordParameterName

  # Phase 4 - Compute (needs subnets/SGs + EFS FS ID + RDS endpoint + creds)
  Phase4Compute:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref Phase4TemplateUrl
      Parameters:
        VpcId: !GetAtt Phase1Network.Outputs.VpcId
        PublicSubnetAId: !GetAtt Phase1Network.Outputs.PublicSubnetAId
        PublicSubnetBId: !GetAtt Phase1Network.Outputs.PublicSubnetBId
        PrivateSubnetAId: !GetAtt Phase1Network.Outputs.PrivateSubnetAId
        PrivateSubnetBId: !GetAtt Phase1Network.Outputs.PrivateSubnetBId
        AppSecurityGroupId: !GetAtt Phase1Network.Outputs.AppSecurityGroupId
        AlbSecurityGroupId: !GetAtt Phase1Network.Outputs.AlbSecurityGroupId
        KeyPairName: !Ref KeyPairName
        WebsiteContentBucketName: !Ref WebsiteContentBucketName
        EfsFileSystemId: !GetAtt Phase2EFS.Outputs.FileSystemId
        RdsEndpointAddress: !GetAtt Phase3RDS.Outputs.DBEndpointAddress
        DbUsername: !Ref DbUsername
        DbPasswordParameterName: !Ref DbPasswordParameterName

  # Phase 5 - DNS/Failover (needs ALB + backup S3 website domain)
  Phase5DNS:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref Phase5TemplateUrl
      Parameters:
        DomainName: !Ref DomainName
        AlbDNSName: !GetAtt Phase4Compute.Outputs.AlbDNSName
        AlbHostedZoneId: !GetAtt Phase4Compute.Outputs.AlbHostedZoneId
        # S3WebsiteHostedZoneId can be omitted (Phase 5 has a default for us-east-1)
        # HealthCheckPath uses child default "/"

Outputs:
  AlbDNSName:
    Value: !GetAtt Phase4Compute.Outputs.AlbDNSName

  HostedZoneId:
    Value: !GetAtt Phase5DNS.Outputs.HostedZoneId

  VpcId:
    Value: !GetAtt Phase1Network.Outputs.VpcId
